// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace PacketFbs
{

  using global::System;
  using global::System.Collections.Generic;
  using global::Google.FlatBuffers;

  public struct Ack : IFlatbufferObject
  {
    private Table __p;
    public ByteBuffer ByteBuffer { get { return __p.bb; } }
    public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_24_3_25(); }
    public static Ack GetRootAsAck(ByteBuffer _bb) { return GetRootAsAck(_bb, new Ack()); }
    public static Ack GetRootAsAck(ByteBuffer _bb, Ack obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
    public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
    public Ack __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

    public string Uid { get { int o = __p.__offset(4); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetUidBytes() { return __p.__vector_as_span<byte>(4, 1); }
#else
    public ArraySegment<byte>? GetUidBytes() { return __p.__vector_as_arraysegment(4); }
#endif
    public byte[] GetUidArray() { return __p.__vector_as_array<byte>(4); }

    public static Offset<PacketFbs.Ack> CreateAck(FlatBufferBuilder builder,
        StringOffset uidOffset = default(StringOffset))
    {
      builder.StartTable(1);
      Ack.AddUid(builder, uidOffset);
      return Ack.EndAck(builder);
    }

    public static void StartAck(FlatBufferBuilder builder) { builder.StartTable(1); }
    public static void AddUid(FlatBufferBuilder builder, StringOffset uidOffset) { builder.AddOffset(0, uidOffset.Value, 0); }
    public static Offset<PacketFbs.Ack> EndAck(FlatBufferBuilder builder)
    {
      int o = builder.EndTable();
      return new Offset<PacketFbs.Ack>(o);
    }
  }


  static public class AckVerify
  {
    static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
    {
      return verifier.VerifyTableStart(tablePos)
        && verifier.VerifyString(tablePos, 4 /*Uid*/, false)
        && verifier.VerifyTableEnd(tablePos);
    }
  }

}
