// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace PacketFbs
{

  using global::System;
  using global::System.Collections.Generic;
  using global::Google.FlatBuffers;

  public struct Handshake : IFlatbufferObject
  {
    private Table __p;
    public ByteBuffer ByteBuffer { get { return __p.bb; } }
    public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_24_3_25(); }
    public static Handshake GetRootAsHandshake(ByteBuffer _bb) { return GetRootAsHandshake(_bb, new Handshake()); }
    public static Handshake GetRootAsHandshake(ByteBuffer _bb, Handshake obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
    public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
    public Handshake __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

    public string Uid { get { int o = __p.__offset(4); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetUidBytes() { return __p.__vector_as_span<byte>(4, 1); }
#else
    public ArraySegment<byte>? GetUidBytes() { return __p.__vector_as_arraysegment(4); }
#endif
    public byte[] GetUidArray() { return __p.__vector_as_array<byte>(4); }

    public static Offset<PacketFbs.Handshake> CreateHandshake(FlatBufferBuilder builder,
        StringOffset uidOffset = default(StringOffset))
    {
      builder.StartTable(1);
      Handshake.AddUid(builder, uidOffset);
      return Handshake.EndHandshake(builder);
    }

    public static void StartHandshake(FlatBufferBuilder builder) { builder.StartTable(1); }
    public static void AddUid(FlatBufferBuilder builder, StringOffset uidOffset) { builder.AddOffset(0, uidOffset.Value, 0); }
    public static Offset<PacketFbs.Handshake> EndHandshake(FlatBufferBuilder builder)
    {
      int o = builder.EndTable();
      return new Offset<PacketFbs.Handshake>(o);
    }
  }


  static public class HandshakeVerify
  {
    static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
    {
      return verifier.VerifyTableStart(tablePos)
        && verifier.VerifyString(tablePos, 4 /*Uid*/, false)
        && verifier.VerifyTableEnd(tablePos);
    }
  }

}
