// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace PacketFbs
{

  using global::System;
  using global::System.Collections.Generic;
  using global::Google.FlatBuffers;

  public struct Response : IFlatbufferObject
  {
    private Table __p;
    public ByteBuffer ByteBuffer { get { return __p.bb; } }
    public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_24_3_25(); }
    public static Response GetRootAsResponse(ByteBuffer _bb) { return GetRootAsResponse(_bb, new Response()); }
    public static Response GetRootAsResponse(ByteBuffer _bb, Response obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
    public static bool VerifyResponse(ByteBuffer _bb) { Google.FlatBuffers.Verifier verifier = new Google.FlatBuffers.Verifier(_bb); return verifier.VerifyBuffer("", false, ResponseVerify.Verify); }
    public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
    public Response __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

    public string Mid { get { int o = __p.__offset(4); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetMidBytes() { return __p.__vector_as_span<byte>(4, 1); }
#else
    public ArraySegment<byte>? GetMidBytes() { return __p.__vector_as_arraysegment(4); }
#endif
    public byte[] GetMidArray() { return __p.__vector_as_array<byte>(4); }
    public string Route { get { int o = __p.__offset(6); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetRouteBytes() { return __p.__vector_as_span<byte>(6, 1); }
#else
    public ArraySegment<byte>? GetRouteBytes() { return __p.__vector_as_arraysegment(6); }
#endif
    public byte[] GetRouteArray() { return __p.__vector_as_array<byte>(6); }
    public byte Data(int j) { int o = __p.__offset(8); return o != 0 ? __p.bb.Get(__p.__vector(o) + j * 1) : (byte)0; }
    public int DataLength { get { int o = __p.__offset(8); return o != 0 ? __p.__vector_len(o) : 0; } }
#if ENABLE_SPAN_T
  public Span<byte> GetDataBytes() { return __p.__vector_as_span<byte>(8, 1); }
#else
    public ArraySegment<byte>? GetDataBytes() { return __p.__vector_as_arraysegment(8); }
#endif
    public byte[] GetDataArray() { return __p.__vector_as_array<byte>(8); }

    public static Offset<PacketFbs.Response> CreateResponse(FlatBufferBuilder builder,
        StringOffset midOffset = default(StringOffset),
        StringOffset routeOffset = default(StringOffset),
        VectorOffset dataOffset = default(VectorOffset))
    {
      builder.StartTable(3);
      Response.AddData(builder, dataOffset);
      Response.AddRoute(builder, routeOffset);
      Response.AddMid(builder, midOffset);
      return Response.EndResponse(builder);
    }

    public static void StartResponse(FlatBufferBuilder builder) { builder.StartTable(3); }
    public static void AddMid(FlatBufferBuilder builder, StringOffset midOffset) { builder.AddOffset(0, midOffset.Value, 0); }
    public static void AddRoute(FlatBufferBuilder builder, StringOffset routeOffset) { builder.AddOffset(1, routeOffset.Value, 0); }
    public static void AddData(FlatBufferBuilder builder, VectorOffset dataOffset) { builder.AddOffset(2, dataOffset.Value, 0); }
    public static VectorOffset CreateDataVector(FlatBufferBuilder builder, byte[] data) { builder.StartVector(1, data.Length, 1); for (int i = data.Length - 1; i >= 0; i--) builder.AddByte(data[i]); return builder.EndVector(); }
    public static VectorOffset CreateDataVectorBlock(FlatBufferBuilder builder, byte[] data) { builder.StartVector(1, data.Length, 1); builder.Add(data); return builder.EndVector(); }
    public static VectorOffset CreateDataVectorBlock(FlatBufferBuilder builder, ArraySegment<byte> data) { builder.StartVector(1, data.Count, 1); builder.Add(data); return builder.EndVector(); }
    public static VectorOffset CreateDataVectorBlock(FlatBufferBuilder builder, IntPtr dataPtr, int sizeInBytes) { builder.StartVector(1, sizeInBytes, 1); builder.Add<byte>(dataPtr, sizeInBytes); return builder.EndVector(); }
    public static void StartDataVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(1, numElems, 1); }
    public static Offset<PacketFbs.Response> EndResponse(FlatBufferBuilder builder)
    {
      int o = builder.EndTable();
      return new Offset<PacketFbs.Response>(o);
    }
    public static void FinishResponseBuffer(FlatBufferBuilder builder, Offset<PacketFbs.Response> offset) { builder.Finish(offset.Value); }
    public static void FinishSizePrefixedResponseBuffer(FlatBufferBuilder builder, Offset<PacketFbs.Response> offset) { builder.FinishSizePrefixed(offset.Value); }
  }


  static public class ResponseVerify
  {
    static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
    {
      return verifier.VerifyTableStart(tablePos)
        && verifier.VerifyString(tablePos, 4 /*Mid*/, false)
        && verifier.VerifyString(tablePos, 6 /*Route*/, false)
        && verifier.VerifyVectorOfData(tablePos, 8 /*Data*/, 1 /*byte*/, false)
        && verifier.VerifyTableEnd(tablePos);
    }
  }

}
